// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCExBGFOExxi5fcXaRjJTrSXKgrnOS25fw',
    appId: '1:60706620911:web:4d9ad46314895f7e9b621a',
    messagingSenderId: '60706620911',
    projectId: 'catalog-final-cbd15',
    authDomain: 'catalog-final-cbd15.firebaseapp.com',
    storageBucket: 'catalog-final-cbd15.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDny6TKBlDNHyjuNLgIdv2PVIbX3BVZN74',
    appId: '1:60706620911:android:ad4e33554ac3ea849b621a',
    messagingSenderId: '60706620911',
    projectId: 'catalog-final-cbd15',
    storageBucket: 'catalog-final-cbd15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRqxf85bDKjnDy_s0KWHaQsCOaSG2Ys6Y',
    appId: '1:60706620911:ios:63591ef5d47ac1b49b621a',
    messagingSenderId: '60706620911',
    projectId: 'catalog-final-cbd15',
    storageBucket: 'catalog-final-cbd15.appspot.com',
    iosClientId: '60706620911-ipo38esreidg8koca661nrdsptj9g2pm.apps.googleusercontent.com',
    iosBundleId: 'com.example.catalogFurnitureFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRqxf85bDKjnDy_s0KWHaQsCOaSG2Ys6Y',
    appId: '1:60706620911:ios:63591ef5d47ac1b49b621a',
    messagingSenderId: '60706620911',
    projectId: 'catalog-final-cbd15',
    storageBucket: 'catalog-final-cbd15.appspot.com',
    iosClientId: '60706620911-ipo38esreidg8koca661nrdsptj9g2pm.apps.googleusercontent.com',
    iosBundleId: 'com.example.catalogFurnitureFinal',
  );
}
